if-no-files-found: error

diff --git a/.github/workflows/build-and-publish-reusable-workflow.yml b/.github/workflows/build-and-publish-reusable-workflow.yml
--- a/.github/workflows/build-and-publish-reusable-workflow.yml
+++ b/.github/workflows/build-and-publish-reusable-workflow.yml
@@ -141,32 +141,29 @@ jobs:
       - name: Build
         run: npm run build
 
-      - name: Upload Linux Artifact
-        uses: actions/upload-artifact@v2
-        if: matrix.os == 'linux'
-        with:
-          name: ${{ matrix.os }}
-          path: electron/dist/${{ inputs.app-name }}.tar.gz 
-      - name: Upload Mac Artifact
-        uses: actions/upload-artifact@v2
-        if: matrix.os == 'mac'
-        with:
-          name: ${{ matrix.os }}
-          path: electron/dist/${{ inputs.app-name }}.app.zip
-      - name: Upload Windows Artifact 
-        uses: actions/upload-artifact@v2
-        if: matrix.os == 'windows'
-        with:
-          name: ${{ matrix.os }}
-          path: electron/dist/${{ inputs.app-name }}.zip
-      - name: Upload Android Artifact
-        uses: actions/upload-artifact@v2
-        if: matrix.os == 'android'
-        with:
-          name: ${{ matrix.os }}
-          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
+      - name: Set Artifact Path
+        id: set_path
+        run: |
+          if [[ "${{ matrix.os }}" == "android" ]]; then
+            echo "android/app/build/outputs/apk/release/app-release-unsigned.apk" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.os }}" == "linux" ]]; then
+            echo "electron/dist/${{ inputs.app-name }}.tar.gz" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.os }}" == "mac" ]]; then
+            echo "electron/dist/${{ inputs.app-name }}.app.zip" >> "$GITHUB_OUTPUT"
+          elif [[ "${{ matrix.os }}" == "windows" ]]; then
+            echo "electron/dist/${{ inputs.app-name }}.zip" >> "$GITHUB_OUTPUT"
+          else
+            echo "Invalid OS"
+            exit 1
+          fi
+        shell: bash
 
-
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.os }}
+          path: ${{ steps.set_path.outputs.stdout }} 
+          if-no-files-found: error
   release:
     needs:
       - build
